version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    # Caso precise de variáveis de ambiente
    # environment:
    #   - NODE_ENV=production 